---
collections:
  - name: cloud.azure_roles
    src: https://github.com/ansible-collections/cloud.azure_roles/
  
  - name: redhat.rhel_system_roles
    src: https://aap-ah.ekeberg.io/api/galaxy/content/rh-certified/
  
  - name: redhatinsights.insights
    src: https://aap-ah.ekeberg.io/api/galaxy/content/rh-certified/

  - name: microsoft.sql
    src: https://aap-ah.ekeberg.io/api/galaxy/content/rh-certified/